import { toolPageHtml } from '../components/tool-page.js';
import { tradeHistorySeries, tradeHistoryChartHtml } from '../components/trade-history-chart.js';
import { bindLogTableRows } from '../components/log-table.js';
import { initTableSort, sortHeaderHtml } from '../utils/table-sort.js';
import { bindCalcSticky } from '../utils/calc-sticky.js';
import { escapeHtml } from '../utils/utils.js';
import { formatRelativeDateTime } from '../utils/format.js';
import { itemIconHtml, itemLabel } from '../components/item-icon.js';
import { cityColorHex } from '../components/city-picker.js';
import { initNav } from '../core/nav.js';
import { getAll, initStore, updateRow } from '../db/store.js';
import { getItemUniqueName } from '../db/relations.js';
import { loadActiveCities } from '../core/cities.js';
import { showPageLoader, hidePageLoader } from '../components/loader.js';
import { initFloatingLabels } from '../components/forms.js';
import { recordCurrentToolVisit } from '../core/usage.js';
import { FIXED_PRICE_TABLE as V2_FIXED_PRICE_TABLE } from '../core/fixed-prices.js';
import { bindTradeLive, fetchTradeSnapshot, isTradeLiveConnected, startTradeLive, getLastTradeEventAt } from '../core/trade-live.js';

const SUGGESTION_MIN_TRADES = 5, SUGGESTION_CHANGE_THRESHOLD = .01, TABLE_LIMIT = 40, RECENT_TRADE_LIMIT = 80;
const KIND_META = Object.freeze({ mail_buy:{label:'Market Buy',side:'buy',executed:true}, mail_sell:{label:'Market Sell',side:'sell',executed:true}, mail_buy_expired:{label:'Market Buy Expired',side:'buy'}, mail_sell_expired:{label:'Market Sell Expired',side:'sell'}, blackmarket_sell_expired:{label:'Black Market Expired',side:'sell'}, instant_buy:{label:'Instant Buy',side:'buy',executed:true}, instant_sell:{label:'Instant Sell',side:'sell',executed:true}, crafting:{label:'Crafting',side:'other'}, player_in:{label:'Player Incoming',side:'other'}, player_out:{label:'Player Outgoing',side:'other'} });
const DATE_PRESETS=[{id:'7d',label:'7 gün'},{id:'30d',label:'30 gün'},{id:'90d',label:'90 gün'},{id:'all',label:'Tümü'}], PRICE_METHODS=[{id:'median',label:'Medyan'},{id:'weighted',label:'Ağırlıklı Ort.'},{id:'recent',label:'Son İşlemler'}];
const state={all:[],filtered:[],byId:new Map(),cities:[],live:false,lastEventAt:null,error:null,fixedPrices:[],method:'median',onlyChanges:false,selectedItem:'',filters:{datePreset:'all',city:'',kind:'',itemQuery:'',tier:'',enchant:'',quality:'',search:''}}; let root;
const analysisSorts = new WeakMap();
const kindLabel=(k)=>KIND_META[k]?.label||k||'Unknown', kindSide=(k)=>KIND_META[k]?.side||'other', kindClass=(k)=>`trades-kind-${kindSide(k)}`;
const cityKey=(city)=>String(city??'').toLocaleLowerCase('en-US').replace(/[^a-z0-9]/g,'');
function tradeCity(city){const key=cityKey(city),match=state.cities.find(candidate=>[candidate.name,candidate.displayName,candidate.marketApiName].map(cityKey).some(candidateKey=>candidateKey&&(key===candidateKey||key.startsWith(candidateKey)||candidateKey.startsWith(key))));return match??{marketApiName:key.replace(/market(?:place)?$/,'')};}
const tradeCitySlug=city=>String(tradeCity(city).displayName||city).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const cityDot=(city)=>{const color=cityKey(city).includes('blackmarket')?'#000000':cityColorHex(tradeCity(city));return`<span class="trades-city-dot" style="--trades-city-color:${escapeHtml(color)}" aria-hidden="true"></span>`;};
const formatInt=(v)=>Number.isFinite(Number(v))?Math.round(Number(v)).toLocaleString('tr-TR'):'—', formatSilver=formatInt;
function formatCompact(v){if(!Number.isFinite(Number(v)))return'—';const n=Number(v),a=Math.abs(n),s=n<0?'-':'';if(a>=999500000)return`${s}${Math.round(a/1e9)}B`;if(a>=999500)return`${s}${Math.round(a/1e6)}M`;if(a>=1e3)return`${s}${Math.round(a/1e3)}K`;return formatInt(n);}
function formatDateTime(v){const d=new Date(v);return Number.isNaN(d.getTime())?'—':`${d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})} ${d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false})}`;}
function formatTime(v){const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});}
function median(values){if(!values.length)return null;const v=[...values].sort((a,b)=>a-b),m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2;}
function enrich(raw){const id=String(raw.itemId||''),tier=Number((id.match(/(?:^|_)T(\d)/i)||[])[1])||null,enchant=Number((id.match(/@(\d+)$/)||[])[1])||0;return{...raw,tier,enchant,quality:raw.quality==null?null:Number(raw.quality),cityKey:raw.locationName||(raw.clusterIndex==='@BLACK_MARKET'?'Black Market':raw.clusterIndex||'Unknown'),_ts:Date.parse(raw.occurredAt)||0,_qty:Number(raw.quantity)||0,_total:Number(raw.totalPriceSilver)||0,_unit:Number(raw.unitPriceSilver)||0};}
function identityOf(t){return t.sourceId!=null&&t.sourceId!==''?`id:${t.sourceId}`:`fb:${t.rawType}|${t.clusterIndex}|${t.occurredAt}|${t.itemId}|${t.quantity}|${t.totalPriceSilver}`;}
function periodStart(p){const days={'7d':7,'30d':30,'90d':90}[p];return days?Date.now()-days*86400000:null;}
function matches(t){const f=state.filters,from=periodStart(f.datePreset);if(from&&t._ts<from)return false;if(f.city&&t.cityKey!==f.city)return false;if(f.kind&&t.kind!==f.kind)return false;if(f.itemQuery&&!`${t.itemId||''} ${t.itemName||''}`.toLowerCase().includes(f.itemQuery.toLowerCase()))return false;if(f.tier&&String(t.tier)!==f.tier)return false;if(f.enchant&&String(t.enchant)!==f.enchant)return false;if(f.quality&&String(t.quality)!==f.quality)return false;return!f.search||[t.itemId,t.itemName,t.cityKey,t.counterparty,kindLabel(t.kind)].join(' ').toLowerCase().includes(f.search.toLowerCase());}
function recompute(){state.filtered=state.all.filter(matches).sort((a,b)=>b._ts-a._ts);}
function ingest(trades,reset=false){if(reset){state.all=[];state.byId=new Map();}for(const raw of trades||[]){const t=enrich(raw);t._uid=identityOf(t);if(state.byId.has(t._uid))continue;state.byId.set(t._uid,t);state.all.push(t);}recompute();}
function computeKpis(list){let buy=0,sell=0,total=0,qty=0,today=0;const vals=[],start=new Date();start.setHours(0,0,0,0);list.forEach(t=>{total+=t._total;qty+=t._qty;vals.push(t._total);if(t._ts>=start.getTime())today++;if(kindSide(t.kind)==='buy')buy+=t._total;if(kindSide(t.kind)==='sell')sell+=t._total;});return{count:list.length,total,buy,sell,net:sell-buy,qty,avg:list.length?total/list.length:0,median:median(vals)||0,today,last:list[0]?.occurredAt};}
function aggregateItems(list){const map=new Map();list.forEach(t=>{const key=t.itemId||t.itemName||'unknown';let r=map.get(key);if(!r){r={itemId:t.itemId,itemName:t.itemName||t.itemId||'—',trades:0,qty:0,total:0,prices:[]};map.set(key,r);}r.trades++;r.qty+=t._qty;r.total+=t._total;if(t._unit>0)r.prices.push(t._unit);});return[...map.values()].map(r=>({...r,avg:r.qty?r.total/r.qty:0,median:median(r.prices)||0})).sort((a,b)=>b.trades-a.trades);}
function aggregateCities(list){const map=new Map();list.forEach(t=>{let r=map.get(t.cityKey);if(!r){r={city:t.cityKey,trades:0,qty:0,silver:0};map.set(t.cityKey,r);}r.trades++;r.qty+=t._qty;r.silver+=t._total;});return[...map.values()].map(r=>({...r,avg:r.qty?r.silver/r.qty:0})).sort((a,b)=>b.trades-a.trades);}
function itemPriceExtremes(itemId){
    let maxSell=null,minBuy=null;
    for(const trade of state.filtered){
        if(trade.itemId!==itemId||!KIND_META[trade.kind]?.executed||!Number.isFinite(trade._unit)||trade._unit<=0)continue;
        if(kindSide(trade.kind)==='sell')maxSell=maxSell==null?trade._unit:Math.max(maxSell,trade._unit);
        else if(kindSide(trade.kind)==='buy')minBuy=minBuy==null?trade._unit:Math.min(minBuy,trade._unit);
    }
    return{maxSell,minBuy};
}
function suggestionRows(){return state.fixedPrices.map(fixed=>{const itemUniqueName=getItemUniqueName(fixed.itemId)||fixed.itemId,side=fixed.role==='input'?'buy':'sell',relevant=state.filtered.filter(t=>kindSide(t.kind)===side&&t.itemId===itemUniqueName&&t._unit>0).sort((a,b)=>b._ts-a._ts),qty=relevant.reduce((s,t)=>s+t._qty,0),prices=relevant.map(t=>t._unit);let proposed=null;if(relevant.length>=SUGGESTION_MIN_TRADES){if(state.method==='weighted')proposed=qty?relevant.reduce((s,t)=>s+t._unit*t._qty,0)/qty:null;else if(state.method==='recent')proposed=median(prices.slice(0,Math.min(10,prices.length)));else proposed=median(prices);}proposed=proposed==null?null:Math.round(proposed);const current=Number(fixed.price)||0,diff=proposed==null||!current?null:(proposed-current)/current,changed=diff!=null&&Math.abs(diff)>=SUGGESTION_CHANGE_THRESHOLD;return{fixed,itemUniqueName,side,current,proposed,diff,...itemPriceExtremes(itemUniqueName),trades:relevant.length,changed,itemName:itemLabel(itemUniqueName,relevant[0]?.itemName||itemUniqueName)};}).filter(r=>!state.onlyChanges||r.changed);}
function summary(rows){return rows.reduce((s,r)=>{s.total++;if(r.proposed==null)s.insufficient++;else if(!r.changed)s.same++;else if(r.diff>0)s.up++;else s.down++;return s;},{total:0,up:0,down:0,same:0,insufficient:0});}
function renderShell(){root.innerHTML=toolPageHtml({key:'trades',fillControls:true,head:'<section class="page-head" data-page-head="trades"><h1>Trades</h1><p>İşlem geçmişi ve fiyat önerileri.</p></section>',topControls:'<section class="trades-filters" data-filters aria-label="Filtreler"></section>',controls:'<aside class="trades-panel trades-options" data-options></aside>',result:`<div class="trades-root"><section class="trades-kpi" data-kpi aria-label="Özet"></section><div data-trades-error hidden class="trades-error"></div><section class="trades-main"><section class="trades-panel trades-suggestions"><div class="trades-panel-title"><div><h1>Island Planner Fiyat Önerileri</h1><p>${V2_FIXED_PRICE_TABLE} için işlem verisine dayalı fiyat önerileri.</p></div><span data-live-status class="trades-live"></span></div><div class="trades-panel-body" data-suggestions></div></section></section></div>`,bottomResult:`<section class="trades-bottom"><section class="trades-panel trades-item-analysis"><div class="trades-panel-title"><div><h2>Item Analizi</h2><p>En çok trade yapılan itemler.</p></div></div><div class="trades-panel-body" data-items></div><section class="trades-item-chart" data-item-chart aria-live="polite"></section></section><section class="trades-panel"><div class="trades-panel-title"><div><h2>Şehir Analizi</h2><p>Şehirlere göre trade dağılımı.</p></div></div><div class="trades-panel-body" data-cities></div></section><section class="trades-panel"><div class="trades-panel-title"><div><h2>Trade Geçmişi</h2><p>Son işlemler.</p></div></div><div class="trades-panel-body" data-history></div></section></section>`,overlays:`<dialog class="app-dialog trades-confirm-dialog" data-confirm-dialog><button type="button" class="app-dialog-close" aria-label="Kapat" data-confirm-close></button><div class="trades-confirm-sheet" data-confirm-sheet></div></dialog>`});root.querySelector('[data-confirm-close]').addEventListener('click',()=>root.querySelector('[data-confirm-dialog]').close());}
function selectOptions(items,selected,allLabel='Tümü'){return`<option value="">${allLabel}</option>${items.map(x=>`<option value="${escapeHtml(String(x.id??x))}" ${String(selected)===String(x.id??x)?'selected':''}>${escapeHtml(x.label??String(x))}</option>`).join('')}`;}
function filterSelect(label,filter,options){const id=`trades-filter-${filter}`;return`<select class="form-select" id="${id}" data-filter="${filter}">${options}</select><label for="${id}">${label}</label>`;}
function renderFilters(){const f=state.filters,cities=[...new Set(state.all.map(t=>t.cityKey))].sort((a,b)=>a.localeCompare(b,'tr')),filters=root.querySelector('[data-filters]');filters.innerHTML=`<div class="form-floating">${filterSelect('Tarih','datePreset',DATE_PRESETS.map(x=>`<option value="${x.id}" ${f.datePreset===x.id?'selected':''}>${x.label}</option>`).join(''))}</div><div class="form-floating">${filterSelect('Şehir','city',selectOptions(cities,f.city))}</div><div class="form-floating">${filterSelect('İşlem','kind',selectOptions(Object.entries(KIND_META).map(([id,x])=>({id,label:x.label})),f.kind))}</div><div class="form-floating"><input class="form-control" id="trades-filter-item" data-filter="itemQuery" value="${escapeHtml(f.itemQuery)}" placeholder="Item adı veya ID"><label for="trades-filter-item">Item adı veya ID</label></div><div class="form-floating">${filterSelect('Tier','tier',selectOptions([1,2,3,4,5,6,7,8],f.tier))}</div><div class="form-floating">${filterSelect('Enchant','enchant',selectOptions([0,1,2,3],f.enchant))}</div><div class="form-floating">${filterSelect('Quality','quality',selectOptions([1,2,3,4,5],f.quality))}</div><div class="form-floating"><input class="form-control" id="trades-filter-search" data-filter="search" value="${escapeHtml(f.search)}" placeholder="Genel arama"><label for="trades-filter-search">Genel arama</label></div><div class="trades-filters-actions"><button class="btn btn-primary" type="button" data-apply>Filtreleri Uygula</button><button class="btn btn-outline-secondary" type="button" data-clear>Sıfırla</button></div>`;initFloatingLabels(filters);root.querySelector('[data-apply]').addEventListener('click',()=>{root.querySelectorAll('[data-filter]').forEach(i=>{state.filters[i.dataset.filter]=i.value;});recompute();renderDynamic();});root.querySelector('[data-clear]').addEventListener('click',()=>{state.filters={datePreset:'all',city:'',kind:'',itemQuery:'',tier:'',enchant:'',quality:'',search:''};state.selectedItem='';recompute();renderFilters();renderDynamic();});}
function renderKpi(){const k=computeKpis(state.filtered),cells=[['Toplam Trade',formatInt(k.count),''],['Son İşlem',formatTime(k.last),''],['Toplam Silver',formatCompact(k.total),''],['Toplam Buy',formatCompact(k.buy),'is-pos'],['Toplam Sell',formatCompact(k.sell),'is-neg'],['Net',formatCompact(k.net),k.net>=0?'is-pos':'is-neg'],['Toplam Qty',formatInt(k.qty),''],['Ort. Fiyat',formatCompact(k.avg),''],['Medyan Fiyat',formatCompact(k.median),''],['Bugün',formatInt(k.today),'']];root.querySelector('[data-kpi]').innerHTML=cells.map(([l,v,c])=>`<div class="trades-kpi-item"><span class="trades-kpi-label">${l}</span><strong class="trades-kpi-value ${c}">${v}</strong></div>`).join('');}
function extremePriceHtml(row,side){
    const price=side==='sell'?row.maxSell:row.minBuy;
    if(price==null)return '—';
    const text=formatSilver(price);
    return row.side===side?`<span class="badge trades-side-${side} trades-extreme-tag">${text}</span>`:text;
}
function priceDifferenceHtml(price,current){
    if(price==null||!(current>0))return '';
    const diff=(price-current)/current,style=diff>0?'is-up':diff<0?'is-down':'is-same';
    const title=diff>0?'Mevcut fiyatın üzerinde':diff<0?'Mevcut fiyatın altında':'Mevcut fiyatla aynı';
    return `<span class="trades-diff trades-price-difference ${style}" title="${title}">${Math.round(Math.abs(diff*100))}%</span>`;
}
function suggestionDifferenceHtml(row,{left=false}={}){
    if(row.diff==null)return '';
    const style=row.changed?(row.diff>0?'is-up':'is-down'):'is-same';
    return `<sup class="trades-diff trades-suggestion-diff${left?' trades-suggestion-diff--left':''} ${style}">${Math.round(Math.abs(row.diff*100))}%</sup>`;
}
function suggestionPosition(row){
    if(row.proposed==null)return row.side==='buy'?'between-buy':'between-sell';
    if(row.minBuy!=null&&row.proposed<Math.min(row.minBuy,row.current))return 'outside-buy';
    if(row.maxSell!=null&&row.proposed>Math.max(row.maxSell,row.current))return 'outside-sell';
    return row.proposed<row.current?'between-buy':'between-sell';
}
function suggestionSide(row){return suggestionPosition(row).endsWith('buy')?'buy':'sell';}
function currentPriceHtml(row){
    if(row.diff==null||row.changed)return formatSilver(row.current);
    return `<span class="trades-suggestion-price"><button type="button" class="badge trades-price-action is-unchanged" data-apply-price="${row.fixed.id}" title="Mevcut fiyat · Yakın öneriyi uygula" aria-label="Mevcut fiyat: ${formatSilver(row.current)}, önerilen fiyatı uygula: ${formatSilver(row.proposed)}">${formatSilver(row.current)}</button>${suggestionDifferenceHtml(row,{left:suggestionSide(row)==='sell'})}</span>`;
}
function suggestedPriceHtml(row){
    if(row.diff!=null&&!row.changed)return '';
    if(row.proposed==null)return '<span class="trades-suggestion-price"><button type="button" class="badge trades-price-action is-insufficient" disabled title="Yeterli veri yok" aria-label="Fiyat önerisi için yeterli veri yok">—</button></span>';
    const difference=suggestionDifferenceHtml(row);
    return `<span class="trades-suggestion-price"><button type="button" class="badge trades-price-action ${row.changed?'is-applicable':'is-unchanged'}" data-apply-price="${row.fixed.id}" title="${row.changed?'Uygulanabilir · Önerilen fiyatı uygula':'Değişiklik yok · Önerilen fiyatı uygula'}" aria-label="${row.changed?'Uygulanabilir':'Değişiklik yok'}: ${formatSilver(row.proposed)}">${formatSilver(row.proposed)}</button>${difference}</span>`;
}
const SUGGESTION_PRICE_COLUMNS = [{"key":"outside-sell"},{"key":"maxSell","label":"Max Satış"},{"key":"between-sell"},{"key":"current","label":"Mevcut"},{"key":"between-buy"},{"key":"minBuy","label":"Min Alış"},{"key":"outside-buy"}];
function suggestionPriceCells(row){
    return SUGGESTION_PRICE_COLUMNS.map(column=>{
        let content;
        if(column.key==='current')content=currentPriceHtml(row);
        else if(column.key==='maxSell')content=`<span class="trades-price-pair trades-price-pair--sell">${extremePriceHtml(row,'sell')}${priceDifferenceHtml(row.maxSell,row.current)}</span>`;
        else if(column.key==='minBuy')content=`<span class="trades-price-pair trades-price-pair--buy">${priceDifferenceHtml(row.minBuy,row.current)}${extremePriceHtml(row,'buy')}</span>`;
        else content=suggestionPosition(row)===column.key?suggestedPriceHtml(row):'';
        return `<td class="num ${column.label?'trades-price-column':'trades-suggestion-column'}">${content}</td>`;
    }).join('');
}
function renderSuggestions(){const rows=suggestionRows();root.querySelector('[data-suggestions]').innerHTML=`<table class="table table-striped log-table calc-table trades-table"><colgroup><col>${SUGGESTION_PRICE_COLUMNS.map(column=>`<col class="${column.label?'trades-price-column':'trades-suggestion-column'}">`).join('')}<col class="trades-count-column"></colgroup><thead><tr><th>Item</th>${SUGGESTION_PRICE_COLUMNS.map(column=>`<th class="num ${column.label?'trades-price-column':'trades-suggestion-column'}">${column.label||''}</th>`).join('')}<th class="num">Trade</th></tr></thead><tbody>${rows.map(r=>{return`<tr data-id="${escapeHtml(r.itemUniqueName)}" class="${state.selectedItem===r.itemUniqueName?'table-active':''}" tabindex="0" aria-selected="${state.selectedItem===r.itemUniqueName}" title="Alt tabloları bu iteme göre filtrele; tekrar tıklayarak kaldır"><td title="${escapeHtml(r.itemUniqueName)}"><span class="trades-table-identity"><span class="badge trades-side-${r.side}">${r.side.toUpperCase()}</span>${itemIconHtml(r.itemUniqueName,{size:48,className:'item-icon trades-table-item-icon'})}<span>${escapeHtml(r.itemName)}</span></span></td>${suggestionPriceCells(r)}<td class="num">${formatInt(r.trades)}</td></tr>`;}).join('')||'<tr><td colspan="${SUGGESTION_PRICE_COLUMNS.length+2}" class="trades-empty">Bu kapsamda sabit fiyat kaydı yok.</td></tr>'}</tbody></table>`;root.querySelectorAll('[data-apply-price]').forEach(b=>b.addEventListener('click',event=>{event.stopPropagation();openConfirmation(Number(b.dataset.applyPrice));}));const host=root.querySelector('[data-suggestions]');bindLogTableRows(host,itemId=>{state.selectedItem=state.selectedItem===itemId?'':itemId;renderSuggestions();renderAnalysis();bindCalcSticky(root);});host.querySelectorAll('tr[data-id]').forEach(row=>row.addEventListener('keydown',event=>{if(event.target===row&&(event.key==='Enter'||event.key===' ')){event.preventDefault();row.click();}}));}
function renderOptions(){const rows=suggestionRows(),s=summary(rows);root.querySelector('[data-options]').innerHTML=`<div class="trades-options-controls"><div class="farming-type" style="width:100%" role="radiogroup" aria-label="Hesaplama yöntemi">${PRICE_METHODS.map(m=>`<button type="button" class="farming-type-btn price-side-btn flex-grow-1${state.method===m.id?' is-active':''}" data-price-method="${m.id}" aria-pressed="${state.method===m.id?'true':'false'}">${m.label}</button>`).join('')}</div><div class="farming-type" style="width:100%" role="radiogroup" aria-label="Dönem">${DATE_PRESETS.map(x=>`<button type="button" class="farming-type-btn price-side-btn flex-grow-1${state.filters.datePreset===x.id?' is-active':''}" data-period-preset="${x.id}" aria-pressed="${state.filters.datePreset===x.id?'true':'false'}">${x.label}</button>`).join('')}</div><label class="form-check"><input class="form-check-input" type="checkbox" data-only-changes ${state.onlyChanges?'checked':''}><span class="form-check-label">Sadece değişmesi gerekenleri göster</span></label></div><div class="trades-options-section trades-summary"><h2>Öneri Özeti</h2><dl><dt>Toplam Öneri</dt><dd>${s.total}</dd><dt class="is-up">Fiyat Artır</dt><dd class="is-up">${s.up}</dd><dt class="is-down">Fiyat Düşür</dt><dd class="is-down">${s.down}</dd><dt>Değişiklik Yok</dt><dd>${s.same}</dd><dt class="trades-warning">Yeterli Veri Yok</dt><dd class="trades-warning">${s.insufficient}</dd></dl></div>`;root.querySelectorAll('[data-price-method]').forEach(button=>button.addEventListener('click',()=>{state.method=button.dataset.priceMethod;renderDynamic();}));root.querySelectorAll('[data-period-preset]').forEach(button=>button.addEventListener('click',()=>{state.filters.datePreset=button.dataset.periodPreset;recompute();renderFilters();renderDynamic();}));root.querySelector('[data-only-changes]').addEventListener('change',e=>{state.onlyChanges=e.target.checked;renderDynamic();});}
function renderSimpleTable(host,headers,rows,body,empty){host.innerHTML=`<table class="table table-striped log-table calc-table trades-table"><thead><tr>${headers.map((x,index)=>sortHeaderHtml(x.label,{key:String(index),type:x.type||(x.num?'number':'text'),className:x.num?'num':''})).join('')}</tr></thead><tbody>${rows.map(body).join('')||`<tr><td colspan="${headers.length}" class="trades-empty">${empty}</td></tr>`}</tbody></table>`;initTableSort(host.querySelector('table'),{initial:analysisSorts.get(host),onSort:({key,direction})=>analysisSorts.set(host,{key,direction})});}
function analysisTrades(){return state.selectedItem?state.filtered.filter(t=>t.itemId===state.selectedItem):state.filtered;}
function renderAnalysis(){renderItems();renderCities();renderHistory();renderItemChart();}
function renderItemChart(){
    const trades=state.selectedItem?analysisTrades():[];
    const series=tradeHistorySeries(trades,city=>({key:tradeCitySlug(city),label:tradeCity(city).displayName||city}));
    root.querySelector('[data-item-chart]').innerHTML=tradeHistoryChartHtml(series,{itemName:state.selectedItem?itemLabel(state.selectedItem,trades[0]?.itemName||state.selectedItem):'',formatPrice:formatSilver,formatDate:formatDateTime});
}
function renderItems(){renderSimpleTable(root.querySelector('[data-items]'),[{label:'Item'},{label:'Trade',num:true},{label:'Qty',num:true},{label:'Ort. Fiyat',num:true},{label:'Medyan',num:true}],aggregateItems(analysisTrades()).slice(0,TABLE_LIMIT),r=>`<tr><td title="${escapeHtml(r.itemId||'')}"><span class="trades-table-identity">${itemIconHtml(r.itemId,{size:24,className:'item-icon trades-table-item-icon'})}<span class="trades-table-name">${escapeHtml(r.itemName)}</span></span></td><td class="num" data-sort-value="${r.trades}">${formatInt(r.trades)}</td><td class="num" data-sort-value="${r.qty}">${formatCompact(r.qty)}</td><td class="num" data-sort-value="${r.avg}">${formatSilver(r.avg)}</td><td class="num" data-sort-value="${r.median}">${formatSilver(r.median)}</td></tr>`,'Kayıt yok');}
function renderCities(){renderSimpleTable(root.querySelector('[data-cities]'),[{label:'Şehir'},{label:'Trade',num:true},{label:'Qty',num:true},{label:'Hacim',num:true},{label:'Ort. Fiyat',num:true}],aggregateCities(analysisTrades()).slice(0,TABLE_LIMIT),r=>`<tr><td><span class="trades-table-identity">${cityDot(r.city)}<span class="trades-table-name">${escapeHtml(r.city)}</span></span></td><td class="num" data-sort-value="${r.trades}">${formatInt(r.trades)}</td><td class="num" data-sort-value="${r.qty}">${formatCompact(r.qty)}</td><td class="num" data-sort-value="${r.silver}">${formatCompact(r.silver)}</td><td class="num" data-sort-value="${r.avg}">${formatSilver(r.avg)}</td></tr>`,'Kayıt yok');}
function renderHistory(){renderSimpleTable(root.querySelector('[data-history]'),[{label:'Tarih',type:'number'},{label:'Şehir'},{label:'Item'},{label:'İşlem'},{label:'Qty',num:true},{label:'Fiyat',num:true},{label:'Toplam',num:true}],analysisTrades().filter(t=>t.kind!=='crafting').slice(0,RECENT_TRADE_LIMIT),t=>`<tr data-city="${escapeHtml(tradeCitySlug(t.cityKey))}"><td data-sort-value="${t._ts}" title="${escapeHtml(new Date(t._ts).toLocaleString('tr-TR'))}">${formatRelativeDateTime(t.occurredAt)}</td><td>${escapeHtml(t.cityKey)}</td><td title="${escapeHtml(t.itemId||'')}">${escapeHtml(t.itemName||t.itemId||'—')}</td><td class="${kindClass(t.kind)}">${escapeHtml(kindLabel(t.kind))}</td><td class="num" data-sort-value="${t._qty}">${formatCompact(t._qty)}</td><td class="num" data-sort-value="${t._unit}">${formatSilver(t._unit)}</td><td class="num" data-sort-value="${t._total}">${formatSilver(t._total)}</td></tr>`,'Kayıt yok');}
function openConfirmation(id){const r=suggestionRows().find(x=>Number(x.fixed.id)===id);if(!r||r.proposed==null)return;const direction=r.proposed<r.current?'down':r.proposed>r.current?'up':'same',action=direction==='down'?'Düşür':direction==='up'?'Yükselt':'Uygula';const sheet=root.querySelector('[data-confirm-sheet]');sheet.innerHTML=`<h2>Fiyat önerisini uygula</h2><p><strong>${escapeHtml(r.itemName)}</strong> için <span class="badge trades-side-${r.side}">${r.side.toUpperCase()}</span> fiyatını güncellemek istiyor musunuz?</p><dl class="trades-confirm-values"><dt>Mevcut fiyat</dt><dd>${formatSilver(r.current)}</dd><dt class="trades-confirm-proposed-label">Önerilen fiyat</dt><dd class="trades-confirm-proposed">${direction==='same'?'':`<span class="trades-confirm-arrow" aria-hidden="true">${direction==='down'?'↓':'↑'}</span>`}${formatSilver(r.proposed)}</dd></dl><div class="trades-confirm-actions"><button class="btn btn-outline-secondary" type="button" data-confirm-cancel>Vazgeç</button><button class="btn ${direction==='down'?'btn-danger':direction==='up'?'btn-success':'btn-primary'}" type="button" data-confirm-apply>${action}</button></div>`;const dialog=root.querySelector('[data-confirm-dialog]');sheet.querySelector('[data-confirm-cancel]').addEventListener('click',()=>dialog.close());sheet.querySelector('[data-confirm-apply]').addEventListener('click',()=>{const data=new FormData();data.set('itemId',r.fixed.itemId);data.set('role',r.fixed.role);data.set('price',String(r.proposed));updateRow(V2_FIXED_PRICE_TABLE,r.fixed.id,data);state.fixedPrices=getAll(V2_FIXED_PRICE_TABLE);dialog.close();renderDynamic();});dialog.showModal();}
function renderError(){const el=root.querySelector('[data-trades-error]');el.hidden=!state.error;el.textContent=state.error||'';}function renderLive(){const el=root.querySelector('[data-live-status]');el.textContent=state.live?`LIVE · ${formatTime(state.lastEventAt||getLastTradeEventAt())}`:'BAĞLANTI YOK';el.classList.toggle('is-live',state.live);}function renderDynamic(){renderError();renderLive();renderKpi();renderSuggestions();renderOptions();renderAnalysis();bindCalcSticky(root);}
function onLiveEvent(d){if(!d)return;if(d.type==='connection'){state.live=!!d.connected;renderLive();return;}if(d.type==='error'){state.error=d.message||'Trade hub hatası';renderError();return;}if(d.type==='initial'){state.live=true;state.lastEventAt=d.at;ingest(d.trades,true);renderFilters();renderDynamic();}if(d.type==='added'){state.live=true;state.lastEventAt=d.at;ingest(d.trades);renderDynamic();}}
async function main(){root=document.querySelector('[data-trades]');if(!root)return;showPageLoader('Trade analizi yükleniyor…');try{initNav();await initStore();recordCurrentToolVisit();state.cities=loadActiveCities();state.fixedPrices=getAll(V2_FIXED_PRICE_TABLE);renderShell();recompute();renderFilters();renderDynamic();startTradeLive();bindTradeLive(onLiveEvent);state.live=isTradeLiveConnected();const snap=await fetchTradeSnapshot();if(Array.isArray(snap.trades)){state.lastEventAt=snap.at;ingest(snap.trades,true);renderFilters();renderDynamic();}}catch(error){state.error=error.message||String(error);renderError();}finally{hidePageLoader();}}
main();
