import { escapeHtml } from '../utils/utils.js';
import { initNav } from '../core/nav.js';
import { getAll, initStore, updateRow } from '../db/store.js';
import { showPageLoader, hidePageLoader } from '../components/loader.js';
import { recordCurrentToolVisit } from '../core/usage.js';
import { V2_FIXED_PRICE_TABLE } from './island-planner-v2-config.js';
import { bindTradeLive, fetchTradeSnapshot, isTradeLiveConnected, startTradeLive, getLastTradeEventAt } from '../core/trade-live.js';

const SUGGESTION_MIN_TRADES = 5, SUGGESTION_CHANGE_THRESHOLD = .01, TABLE_LIMIT = 40, RECENT_TRADE_LIMIT = 80;
const KIND_META = Object.freeze({ mail_buy:{label:'Market Buy',side:'buy'}, mail_sell:{label:'Market Sell',side:'sell'}, mail_buy_expired:{label:'Market Buy Expired',side:'buy'}, mail_sell_expired:{label:'Market Sell Expired',side:'sell'}, blackmarket_sell_expired:{label:'Black Market Expired',side:'sell'}, instant_buy:{label:'Instant Buy',side:'buy'}, instant_sell:{label:'Instant Sell',side:'sell'}, crafting:{label:'Crafting',side:'other'}, player_in:{label:'Player Incoming',side:'other'}, player_out:{label:'Player Outgoing',side:'other'} });
const DATE_PRESETS=[{id:'7d',label:'7 gün'},{id:'30d',label:'30 gün'},{id:'90d',label:'90 gün'},{id:'all',label:'Tümü'}], PRICE_METHODS=[{id:'median',label:'Medyan'},{id:'weighted',label:'Ağırlıklı Ort.'},{id:'recent',label:'Son İşlemler'}];
const state={all:[],filtered:[],byId:new Map(),live:false,lastEventAt:null,error:null,fixedPrices:[],method:'median',onlyChanges:false,filters:{datePreset:'all',city:'',kind:'',itemQuery:'',tier:'',enchant:'',quality:'',search:''}}; let root;
const kindLabel=(k)=>KIND_META[k]?.label||k||'Unknown', kindSide=(k)=>KIND_META[k]?.side||'other', kindClass=(k)=>`trades-kind-${kindSide(k)}`;
const formatInt=(v)=>Number.isFinite(Number(v))?Math.round(Number(v)).toLocaleString('tr-TR'):'—', formatSilver=formatInt;
function formatCompact(v){if(!Number.isFinite(Number(v)))return'—';const n=Number(v),a=Math.abs(n),s=n<0?'-':'';if(a>=1e9)return`${s}${(a/1e9).toFixed(2)}b`;if(a>=1e6)return`${s}${(a/1e6).toFixed(1)}m`;if(a>=1e4)return`${s}${(a/1e3).toFixed(1)}k`;return formatInt(n);}
function formatDateTime(v){const d=new Date(v);return Number.isNaN(d.getTime())?'—':`${d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})} ${d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false})}`;}
function formatTime(v){const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});}
function median(values){if(!values.length)return null;const v=[...values].sort((a,b)=>a-b),m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2;}
function enrich(raw){const id=String(raw.itemId||''),tier=Number((id.match(/(?:^|_)T(\d)/i)||[])[1])||null,enchant=Number((id.match(/@(\d+)$/)||[])[1])||0;return{...raw,tier,enchant,quality:raw.quality==null?null:Number(raw.quality),cityKey:raw.locationName||(raw.clusterIndex==='@BLACK_MARKET'?'Black Market':raw.clusterIndex||'Unknown'),_ts:Date.parse(raw.occurredAt)||0,_qty:Number(raw.quantity)||0,_total:Number(raw.totalPriceSilver)||0,_unit:Number(raw.unitPriceSilver)||0};}
function identityOf(t){return t.sourceId!=null&&t.sourceId!==''?`id:${t.sourceId}`:`fb:${t.rawType}|${t.clusterIndex}|${t.occurredAt}|${t.itemId}|${t.quantity}|${t.totalPriceSilver}`;}
function periodStart(p){const days={'7d':7,'30d':30,'90d':90}[p];return days?Date.now()-days*86400000:null;}
function matches(t){const f=state.filters,from=periodStart(f.datePreset);if(from&&t._ts<from)return false;if(f.city&&t.cityKey!==f.city)return false;if(f.kind&&t.kind!==f.kind)return false;if(f.itemQuery&&!`${t.itemId||''} ${t.itemName||''}`.toLowerCase().includes(f.itemQuery.toLowerCase()))return false;if(f.tier&&String(t.tier)!==f.tier)return false;if(f.enchant&&String(t.enchant)!==f.enchant)return false;if(f.quality&&String(t.quality)!==f.quality)return false;return!f.search||[t.itemId,t.itemName,t.cityKey,t.counterparty,kindLabel(t.kind)].join(' ').toLowerCase().includes(f.search.toLowerCase());}
function recompute(){state.filtered=state.all.filter(matches).sort((a,b)=>b._ts-a._ts);}
function ingest(trades,reset=false){if(reset){state.all=[];state.byId=new Map();}for(const raw of trades||[]){const t=enrich(raw);t._uid=identityOf(t);if(state.byId.has(t._uid))continue;state.byId.set(t._uid,t);state.all.push(t);}recompute();}
function computeKpis(list){let buy=0,sell=0,total=0,qty=0,today=0;const vals=[],start=new Date();start.setHours(0,0,0,0);list.forEach(t=>{total+=t._total;qty+=t._qty;vals.push(t._total);if(t._ts>=start.getTime())today++;if(kindSide(t.kind)==='buy')buy+=t._total;if(kindSide(t.kind)==='sell')sell+=t._total;});return{count:list.length,total,buy,sell,net:sell-buy,qty,avg:list.length?total/list.length:0,median:median(vals)||0,today,last:list[0]?.occurredAt};}
function aggregateItems(list){const map=new Map();list.forEach(t=>{const key=t.itemId||t.itemName||'unknown';let r=map.get(key);if(!r){r={itemId:t.itemId,itemName:t.itemName||t.itemId||'—',trades:0,qty:0,total:0,prices:[]};map.set(key,r);}r.trades++;r.qty+=t._qty;r.total+=t._total;if(t._unit>0)r.prices.push(t._unit);});return[...map.values()].map(r=>({...r,avg:r.qty?r.total/r.qty:0,median:median(r.prices)||0})).sort((a,b)=>b.trades-a.trades);}
function aggregateCities(list){const map=new Map();list.forEach(t=>{let r=map.get(t.cityKey);if(!r){r={city:t.cityKey,trades:0,qty:0,silver:0};map.set(t.cityKey,r);}r.trades++;r.qty+=t._qty;r.silver+=t._total;});return[...map.values()].map(r=>({...r,avg:r.qty?r.silver/r.qty:0})).sort((a,b)=>b.trades-a.trades);}
function suggestionRows(){return state.fixedPrices.map(fixed=>{const side=fixed.role==='input'?'buy':'sell',relevant=state.filtered.filter(t=>kindSide(t.kind)===side&&t.itemId===fixed.itemId&&t._unit>0).sort((a,b)=>b._ts-a._ts),qty=relevant.reduce((s,t)=>s+t._qty,0),prices=relevant.map(t=>t._unit);let proposed=null;if(relevant.length>=SUGGESTION_MIN_TRADES){if(state.method==='weighted')proposed=qty?relevant.reduce((s,t)=>s+t._unit*t._qty,0)/qty:null;else if(state.method==='recent')proposed=median(prices.slice(0,Math.min(10,prices.length)));else proposed=median(prices);}proposed=proposed==null?null:Math.round(proposed);const current=Number(fixed.price)||0,diff=proposed==null||!current?null:(proposed-current)/current,changed=diff!=null&&Math.abs(diff)>=SUGGESTION_CHANGE_THRESHOLD;return{fixed,side,current,proposed,diff,trades:relevant.length,changed,itemName:relevant[0]?.itemName||fixed.itemId};}).filter(r=>!state.onlyChanges||r.changed);}
function summary(rows){return rows.reduce((s,r)=>{s.total++;if(r.proposed==null)s.insufficient++;else if(!r.changed)s.same++;else if(r.diff>0)s.up++;else s.down++;return s;},{total:0,up:0,down:0,same:0,insufficient:0});}
function renderShell(){root.innerHTML=`<div class="trades-root"><div data-trades-error hidden class="trades-error"></div><section class="trades-filters" data-filters aria-label="Filtreler"></section><section class="trades-kpi" data-kpi aria-label="Özet"></section><section class="trades-main"><section class="trades-panel trades-suggestions"><div class="trades-panel-title"><div><h1>Island Planner Fiyat Önerileri</h1><p>${V2_FIXED_PRICE_TABLE} için işlem verisine dayalı fiyat önerileri.</p></div><span data-live-status class="trades-live"></span></div><div class="trades-panel-body" data-suggestions></div></section><aside class="trades-panel trades-options" data-options></aside></section><section class="trades-bottom"><section class="trades-panel"><div class="trades-panel-title"><div><h2>Item Analizi</h2><p>En çok trade yapılan itemler.</p></div></div><div class="trades-panel-body" data-items></div></section><section class="trades-panel"><div class="trades-panel-title"><div><h2>Şehir Analizi</h2><p>Şehirlere göre trade dağılımı.</p></div></div><div class="trades-panel-body" data-cities></div></section><section class="trades-panel"><div class="trades-panel-title"><div><h2>Trade Geçmişi</h2><p>Son işlemler.</p></div></div><div class="trades-panel-body" data-history></div></section></section></div><dialog class="app-dialog trades-confirm-dialog" data-confirm-dialog><button type="button" class="app-dialog-close" aria-label="Kapat" data-confirm-close></button><div class="trades-confirm-sheet" data-confirm-sheet></div></dialog>`;root.querySelector('[data-confirm-close]').addEventListener('click',()=>root.querySelector('[data-confirm-dialog]').close());}
function selectOptions(items,selected,allLabel='Tümü'){return`<option value="">${allLabel}</option>${items.map(x=>`<option value="${escapeHtml(String(x.id??x))}" ${String(selected)===String(x.id??x)?'selected':''}>${escapeHtml(x.label??String(x))}</option>`).join('')}`;}
function renderFilters(){const f=state.filters,cities=[...new Set(state.all.map(t=>t.cityKey))].sort((a,b)=>a.localeCompare(b,'tr'));root.querySelector('[data-filters]').innerHTML=`<div><label class="form-label">Tarih</label><select class="form-select" data-filter="datePreset">${DATE_PRESETS.map(x=>`<option value="${x.id}" ${f.datePreset===x.id?'selected':''}>${x.label}</option>`).join('')}</select></div><div><label class="form-label">Şehir</label><select class="form-select" data-filter="city">${selectOptions(cities,f.city)}</select></div><div><label class="form-label">İşlem</label><select class="form-select" data-filter="kind">${selectOptions(Object.entries(KIND_META).map(([id,x])=>({id,label:x.label})),f.kind)}</select></div><div><label class="form-label">Item</label><input class="form-control" data-filter="itemQuery" value="${escapeHtml(f.itemQuery)}" placeholder="Item adı veya ID"></div><div><label class="form-label">Tier</label><select class="form-select" data-filter="tier">${selectOptions([1,2,3,4,5,6,7,8],f.tier)}</select></div><div><label class="form-label">Enchant</label><select class="form-select" data-filter="enchant">${selectOptions([0,1,2,3],f.enchant)}</select></div><div><label class="form-label">Quality</label><select class="form-select" data-filter="quality">${selectOptions([1,2,3,4,5],f.quality)}</select></div><div class="trades-filter-search"><label class="form-label">Arama</label><input class="form-control" data-filter="search" value="${escapeHtml(f.search)}" placeholder="Eşya adı ara…"></div><div class="trades-filters-actions"><button class="btn btn-primary" type="button" data-apply>Filtreleri Uygula</button><button class="btn btn-outline-secondary" type="button" data-clear>Sıfırla</button></div>`;root.querySelector('[data-apply]').addEventListener('click',()=>{root.querySelectorAll('[data-filter]').forEach(i=>{state.filters[i.dataset.filter]=i.value;});recompute();renderDynamic();});root.querySelector('[data-clear]').addEventListener('click',()=>{state.filters={datePreset:'all',city:'',kind:'',itemQuery:'',tier:'',enchant:'',quality:'',search:''};recompute();renderFilters();renderDynamic();});}
function renderKpi(){const k=computeKpis(state.filtered),cells=[['Toplam Trade',formatInt(k.count),''],['Son İşlem',formatTime(k.last),''],['Toplam Silver',formatCompact(k.total),''],['Toplam Buy',formatCompact(k.buy),'is-pos'],['Toplam Sell',formatCompact(k.sell),'is-neg'],['Net',formatCompact(k.net),k.net>=0?'is-pos':'is-neg'],['Toplam Qty',formatInt(k.qty),''],['Ort. Fiyat',formatCompact(k.avg),''],['Medyan Fiyat',formatCompact(k.median),''],['Bugün',formatInt(k.today),'']];root.querySelector('[data-kpi]').innerHTML=cells.map(([l,v,c])=>`<div class="trades-kpi-item"><span class="trades-kpi-label">${l}</span><strong class="trades-kpi-value ${c}">${v}</strong></div>`).join('');}
function renderSuggestions(){const rows=suggestionRows();root.querySelector('[data-suggestions]').innerHTML=`<table class="table table-striped log-table calc-table trades-table"><thead><tr><th>Item</th><th class="num">Mevcut</th><th class="num">Önerilen</th><th class="num">Fark</th><th class="num">Trade</th><th>Durum</th></tr></thead><tbody>${rows.map(r=>{const diff=r.diff==null?'—':`${(r.diff*100).toFixed(1)}%`,dc=r.diff==null?'':r.changed?(r.diff>0?'is-up':'is-down'):'is-same';return`<tr><td title="${escapeHtml(r.fixed.itemId)}"><span class="badge trades-side-${r.side}">${r.side.toUpperCase()}</span>${escapeHtml(r.itemName)}</td><td class="num">${formatSilver(r.current)}</td><td class="num">${r.proposed==null?'—':`<button type="button" class="btn btn-primary btn-sm trades-price-action" data-apply-price="${r.fixed.id}">${formatSilver(r.proposed)}</button>`}</td><td class="num trades-diff ${dc}">${diff}</td><td class="num">${formatInt(r.trades)}</td><td>${r.proposed==null?'<span class="trades-warning">⚠ Yeterli veri yok</span>':r.changed?'<span class="trades-status-ok">● Uygulanabilir</span>':'<span class="trades-status-muted">Değişiklik yok</span>'}</td></tr>`;}).join('')||'<tr><td colspan="6" class="trades-empty">Bu kapsamda sabit fiyat kaydı yok.</td></tr>'}</tbody></table>`;root.querySelectorAll('[data-apply-price]').forEach(b=>b.addEventListener('click',()=>openConfirmation(Number(b.dataset.applyPrice))));}
function renderOptions(){const rows=suggestionRows(),s=summary(rows);root.querySelector('[data-options]').innerHTML=`<div class="trades-options-section"><h2>Hesaplama Yöntemi</h2>${PRICE_METHODS.map(m=>`<label class="form-check"><input class="form-check-input" type="radio" name="priceMethod" value="${m.id}" ${state.method===m.id?'checked':''}><span class="form-check-label">${m.label}</span></label>`).join('')}</div><div class="trades-options-section"><label class="form-label">Dönem</label><select class="form-select" data-option-period>${DATE_PRESETS.map(x=>`<option value="${x.id}" ${state.filters.datePreset===x.id?'selected':''}>${x.label}</option>`).join('')}</select></div><div class="trades-options-section"><label class="form-check"><input class="form-check-input" type="checkbox" data-only-changes ${state.onlyChanges?'checked':''}><span class="form-check-label">Sadece değişmesi gerekenleri göster</span></label></div><div class="trades-options-section trades-summary"><h2>Öneri Özeti</h2><dl><dt>Toplam Öneri</dt><dd>${s.total}</dd><dt class="is-up">Fiyat Artır</dt><dd class="is-up">${s.up}</dd><dt class="is-down">Fiyat Düşür</dt><dd class="is-down">${s.down}</dd><dt>Değişiklik Yok</dt><dd>${s.same}</dd><dt class="trades-warning">Yeterli Veri Yok</dt><dd class="trades-warning">${s.insufficient}</dd></dl></div>`;root.querySelectorAll('input[name="priceMethod"]').forEach(i=>i.addEventListener('change',()=>{state.method=i.value;renderDynamic();}));root.querySelector('[data-option-period]').addEventListener('change',e=>{state.filters.datePreset=e.target.value;recompute();renderFilters();renderDynamic();});root.querySelector('[data-only-changes]').addEventListener('change',e=>{state.onlyChanges=e.target.checked;renderDynamic();});}
function renderSimpleTable(host,headers,rows,body,empty){host.innerHTML=`<table class="table table-striped log-table calc-table trades-table"><thead><tr>${headers.map(x=>`<th class="${x.num?'num':''}">${x.label}</th>`).join('')}</tr></thead><tbody>${rows.map(body).join('')||`<tr><td colspan="${headers.length}" class="trades-empty">${empty}</td></tr>`}</tbody></table>`;}
function renderItems(){renderSimpleTable(root.querySelector('[data-items]'),[{label:'Item'},{label:'Trade',num:true},{label:'Qty',num:true},{label:'Ort. Fiyat',num:true},{label:'Medyan',num:true}],aggregateItems(state.filtered).slice(0,TABLE_LIMIT),r=>`<tr><td title="${escapeHtml(r.itemId||'')}">${escapeHtml(r.itemName)}</td><td class="num">${formatInt(r.trades)}</td><td class="num">${formatInt(r.qty)}</td><td class="num">${formatSilver(r.avg)}</td><td class="num">${formatSilver(r.median)}</td></tr>`,'Kayıt yok');}
function renderCities(){renderSimpleTable(root.querySelector('[data-cities]'),[{label:'Şehir'},{label:'Trade',num:true},{label:'Qty',num:true},{label:'Hacim',num:true},{label:'Ort. Fiyat',num:true}],aggregateCities(state.filtered).slice(0,TABLE_LIMIT),r=>`<tr><td>${escapeHtml(r.city)}</td><td class="num">${formatInt(r.trades)}</td><td class="num">${formatInt(r.qty)}</td><td class="num">${formatCompact(r.silver)}</td><td class="num">${formatSilver(r.avg)}</td></tr>`,'Kayıt yok');}
function renderHistory(){renderSimpleTable(root.querySelector('[data-history]'),[{label:'Tarih'},{label:'Şehir'},{label:'Item'},{label:'İşlem'},{label:'Qty',num:true},{label:'Fiyat',num:true},{label:'Toplam',num:true}],state.filtered.slice(0,RECENT_TRADE_LIMIT),t=>`<tr><td>${formatDateTime(t.occurredAt)}</td><td>${escapeHtml(t.cityKey)}</td><td title="${escapeHtml(t.itemId||'')}">${escapeHtml(t.itemName||t.itemId||'—')}</td><td class="${kindClass(t.kind)}">${escapeHtml(kindLabel(t.kind))}</td><td class="num">${formatInt(t._qty)}</td><td class="num">${formatSilver(t._unit)}</td><td class="num">${formatSilver(t._total)}</td></tr>`,'Kayıt yok');}
function openConfirmation(id){const r=suggestionRows().find(x=>Number(x.fixed.id)===id);if(!r||r.proposed==null)return;const sheet=root.querySelector('[data-confirm-sheet]');sheet.innerHTML=`<h2>Fiyat önerisini uygula</h2><p><strong>${escapeHtml(r.itemName)}</strong> için <span class="badge trades-side-${r.side}">${r.side.toUpperCase()}</span> fiyatını güncellemek istiyor musunuz?</p><dl class="trades-confirm-values"><dt>Mevcut fiyat</dt><dd>${formatSilver(r.current)}</dd><dt>Önerilen fiyat</dt><dd>${formatSilver(r.proposed)}</dd></dl><div class="trades-confirm-actions"><button class="btn btn-outline-secondary" type="button" data-confirm-cancel>Vazgeç</button><button class="btn btn-primary" type="button" data-confirm-apply>Uygula</button></div>`;const dialog=root.querySelector('[data-confirm-dialog]');sheet.querySelector('[data-confirm-cancel]').addEventListener('click',()=>dialog.close());sheet.querySelector('[data-confirm-apply]').addEventListener('click',()=>{const data=new FormData();data.set('itemId',r.fixed.itemId);data.set('role',r.fixed.role);data.set('price',String(r.proposed));updateRow(V2_FIXED_PRICE_TABLE,r.fixed.id,data);state.fixedPrices=getAll(V2_FIXED_PRICE_TABLE);dialog.close();renderDynamic();});dialog.showModal();}
function renderError(){const el=root.querySelector('[data-trades-error]');el.hidden=!state.error;el.textContent=state.error||'';}function renderLive(){const el=root.querySelector('[data-live-status]');el.textContent=state.live?`LIVE · ${formatTime(state.lastEventAt||getLastTradeEventAt())}`:'BAĞLANTI YOK';el.classList.toggle('is-live',state.live);}function renderDynamic(){renderError();renderLive();renderKpi();renderSuggestions();renderOptions();renderItems();renderCities();renderHistory();}
function onLiveEvent(d){if(!d)return;if(d.type==='connection'){state.live=!!d.connected;renderLive();return;}if(d.type==='error'){state.error=d.message||'Trade hub hatası';renderError();return;}if(d.type==='initial'){state.live=true;state.lastEventAt=d.at;ingest(d.trades,true);renderFilters();renderDynamic();}if(d.type==='added'){state.live=true;state.lastEventAt=d.at;ingest(d.trades);renderDynamic();}}
async function main(){root=document.querySelector('[data-trades]');if(!root)return;showPageLoader('Trade analizi yükleniyor…');try{initNav();await initStore();recordCurrentToolVisit();state.fixedPrices=getAll(V2_FIXED_PRICE_TABLE);renderShell();recompute();renderFilters();renderDynamic();startTradeLive();bindTradeLive(onLiveEvent);state.live=isTradeLiveConnected();const snap=await fetchTradeSnapshot();if(Array.isArray(snap.trades)){state.lastEventAt=snap.at;ingest(snap.trades,true);renderFilters();renderDynamic();}}catch(error){state.error=error.message||String(error);renderError();}finally{hidePageLoader();}}
main();
