// The only authored route registry. Build outputs and runtime catalog rows derive from this list.
export const SITE_ROUTES = [
    { kind: 'page', id: 1, code: 'home', route: '', title: 'Home', source: 'index.html', sortValue: 10 },
    { kind: 'page', id: 2, code: 'db', route: 'db', title: 'Veritabanı', source: 'pages/admin/db.html', sortValue: 20 },
    { kind: 'page', id: 3, code: 'settings', route: 'settings', title: 'Ayarlar', source: 'pages/admin/settings.html', sortValue: 30 },
    { kind: 'tool', id: 1, code: 'daily-bonus', route: 'daily-bonus', title: 'Günlük Bonus', description: 'Her gün iki craft / refine bonusunu kaydedin. Ay içi tekrar sayıları hesaplanır.', icon: '✨', source: 'pages/logs/daily-bonus.html', addedAt: '2026-06-01', groupLabel: 'Kayıt', frequent: true, sortValue: 10, isActive: true },
    { kind: 'tool', id: 14, code: 'island-yields', route: 'island-yields', title: 'Ada Çıktı', description: 'Ada hasat yield’lerini kaydedin; ortalamalar farming ve planlayıcıda kullanılır.', icon: '📊', source: 'pages/logs/island-yields.html', addedAt: '2026-09-13', groupLabel: 'Kayıt', frequent: true, sortValue: 15, isActive: true },
    { kind: 'tool', id: 2, code: 'farmin', route: 'farming', title: 'Farming', description: 'Tarım verimi ve focus; Martlock, Thetford ve Brecilien.', icon: '🌱', source: 'pages/tools/farming.html', addedAt: '2026-09-05', groupLabel: 'Ada', frequent: true, sortValue: 20, isActive: true },
    { kind: 'tool', id: 3, code: 'pasture', route: 'pasture', title: 'Pasture', description: 'Hayvan büyütme, kesme ve süt/yumurta kârı; yem ada veya piyasa.', icon: '🐑', source: 'pages/tools/pasture.html', addedAt: '2026-09-07', groupLabel: 'Ada', frequent: true, sortValue: 30, isActive: true },
    { kind: 'tool', id: 4, code: 'island-planner', route: 'island-planner', title: 'Ada Planlayıcı', description: 'Ham gümüş/gün; sade / zincir / karışık; faction kilit.', icon: '🏝️', source: 'pages/tools/island-planner.html', addedAt: '2026-09-07', groupLabel: 'Ada', frequent: true, sortValue: 40, isActive: true },
    { kind: 'tool', id: 15, code: 'island-planner-v2', route: 'island-planner-v2', title: 'Ada Planlayıcı V2', description: 'Slot tabanlı ada planı; V1 bağımsız olarak korunur.', icon: '🏝️', source: 'pages/tools/island-planner-v2.html', addedAt: '2026-09-20', groupLabel: 'Ada', frequent: false, sortValue: 41, isActive: true },
    { kind: 'tool', id: 16, code: 'trades', route: 'trades', title: 'Trade Dashboard', description: 'SAT trade geçmişi: filtre, özet ve canlı akış.', icon: '📈', source: 'pages/logs/trades.html', addedAt: '2026-09-23', groupLabel: 'Piyasa', frequent: true, sortValue: 45, isActive: true },
    { kind: 'tool', id: 5, code: 'malzemeler', route: 'malzemeler', title: 'Şehir Makası', description: 'Plank, bar, binek: bir şehirden alıp diğerinde satmanın net kârı.', icon: '🪵', source: 'pages/tools/malzemeler.html', addedAt: '2026-09-06', groupLabel: 'Piyasa', frequent: true, sortValue: 50, isActive: true },
    { kind: 'tool', id: 6, code: 'faction', route: 'faction', title: 'Faction', description: 'Crest puan değeri ve faction cape maliyeti / kârı.', icon: '🛡️', source: 'pages/tools/faction.html', addedAt: '2026-08-23', groupLabel: 'Piyasa', frequent: false, sortValue: 60, isActive: true },
    { kind: 'tool', id: 7, code: 'refining', route: 'refining', title: 'Refining', description: 'Ore / logs refine maliyeti, return rate ve kâr.', icon: '🔥', source: 'pages/tools/refining.html', addedAt: '2026-09-05', groupLabel: 'Üretim', frequent: true, sortValue: 70, isActive: true },
    { kind: 'tool', id: 8, code: 'furniture', route: 'furniture', title: 'Furniture', description: 'Ada evi dekorasyonu: sandık, yatak ve masa craft maliyeti / kârı.', icon: '🪑', source: 'pages/tools/furniture.html', addedAt: '2026-09-06', groupLabel: 'Üretim', frequent: true, sortValue: 80, isActive: true },
    { kind: 'tool', id: 9, code: 'house', route: 'house', title: 'House', description: 'Ev ve guild hall yükseltme: oyunun istediği T1 + block, isteğe bağlı ham eşdeğer.', icon: '🏠', source: 'pages/tools/house.html', addedAt: '2026-07-01', groupLabel: 'Üretim', frequent: false, sortValue: 90, isActive: true },
    { kind: 'tool', id: 10, code: 'ava-craft', route: 'ava-craft', title: 'Ava Craft', description: 'Avalonian tool craft maliyeti ve kârı.', icon: '⚡', source: 'pages/tools/ava-craft.html', addedAt: '2026-07-20', groupLabel: 'Üretim', frequent: false, sortValue: 100, isActive: true },
    { kind: 'tool', id: 11, code: 'carleon-craft', route: 'carleon-craft', title: 'Caerleon Craft', description: 'Caerleon / Black Market craft maliyeti ve kârı.', icon: '🗡️', source: 'pages/tools/carleon-craft.html', addedAt: '2026-08-15', groupLabel: 'Üretim', frequent: false, sortValue: 110, isActive: true },
    { kind: 'tool', id: 12, code: 'royal-craft', route: 'royal-craft', title: 'Royal Crafting', description: 'Royal giyilebilir: SET + sigil craft, enchant ve şehir kârı.', icon: '👑', source: 'pages/tools/royal-craft.html', addedAt: '2026-09-13', groupLabel: 'Üretim', frequent: true, sortValue: 115, isActive: true },
    { kind: 'tool', id: 13, code: 'enchantin', route: 'enchanting', title: 'Enchanting', description: 'Rune, soul ve relic: kaçtan kaça çıkarmanın gümüş maliyeti.', icon: '🔮', source: 'pages/tools/enchanting.html', addedAt: '2026-08-23', groupLabel: 'Üretim', frequent: false, sortValue: 120, isActive: true }
];
